spring:
  application:
    name: yosep-payment-service2

  datasource:
    maximum-pool-size: 20
    max-lifetime: 540000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yosep-payment2?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&autoreconnect=true
    username: root
    password: fcsdb1!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format_sql: true
      open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
